#!/usr/bin/env python3
"""Generate the HCDS documentation index without changing document content."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = ROOT / "docs"
OUTPUT = DOCS_ROOT / "05_reference" / "Documentation_Index.md"

PURPOSE_BY_DIR = {
    "docs": "Legacy documentation retained at existing paths",
    "docs/00_governance": "Governance and repository process documentation",
    "docs/01_architecture": "Frozen architecture documentation",
    "docs/02_architecture": "Existing architecture documentation retained at current path",
    "docs/02_schema": "Schema specifications",
    "docs/03_generation": "Future generation documentation",
    "docs/04_pipeline": "Future pipeline documentation",
    "docs/05_reference": "Reference and generated indexes",
}


def title_for(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                return stripped.lstrip("#").strip() or path.stem
    except OSError:
        pass
    return path.stem.replace("_", " ")


def status_for(path: Path) -> str:
    if path == OUTPUT:
        return "Generated"
    if path.stat().st_size == 0:
        return "Empty"
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[:20]:
            if line.startswith("Status:"):
                return line.split(":", 1)[1].strip() or "Existing"
    except OSError:
        pass
    return "Existing"


def main() -> None:
    rows = []
    for path in sorted(DOCS_ROOT.rglob("*.md")):
        if path.name.startswith("._"):
            continue
        rel = path.relative_to(ROOT).as_posix()
        directory = path.parent.relative_to(ROOT).as_posix()
        purpose = PURPOSE_BY_DIR.get(directory, "Documentation")
        rows.append((title_for(path), directory, purpose, status_for(path), rel))

    lines = [
        "# Documentation Index",
        "",
        "This file is generated by `tools/generate_docs_index.py`.",
        "",
        "| Document | Directory | Purpose | Status |",
        "| --- | --- | --- | --- |",
    ]
    for title, directory, purpose, status, rel in rows:
        lines.append(f"| [{title}](../../{rel}) | `{directory}` | {purpose} | {status} |")
    lines.append("")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
